# Generated by Django 2.1 on 2018-08-04 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvl_app', '0003_auto_20180804_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Podróż', 'verbose_name_plural': 'Podróże'},
        ),
        migrations.AlterField(
            model_name='travel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
