# Generated by Django 2.1 on 2018-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvl_app', '0004_auto_20180804_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
